server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://106.75.123.225:3306/springcloud_config?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 13379895997.hui
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 106.75.123.225
      port: 6379
      password: 13379895997.hui

mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句
    map-underscore-to-camel-case: true


